/**
 * Generate VAPID keys and append them to the repo root .env (if not already set).
 *
 * Usage: pnpm --filter @workspace/scripts run setup:vapid
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateVapidKeysForSetup } from "../../artifacts/api-server/src/lib/push/webPushService.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const rootEnv = path.join(root, ".env");
const subject = process.env.VAPID_SUBJECT ?? "mailto:admin@cwpdetailers.com";

function hasVapidKeys(content: string): boolean {
  return /^VAPID_PUBLIC_KEY=\S+/m.test(content) && /^VAPID_PRIVATE_KEY=\S+/m.test(content);
}

function appendVapidBlock(content: string, publicKey: string, privateKey: string): string {
  const block = [
    "",
    "# ── Web Push (PWA browser notifications) ─────────────────────────────────────",
    "# Generated by: pnpm --filter @workspace/scripts run setup:vapid",
    `VAPID_SUBJECT=${subject}`,
    `VAPID_PUBLIC_KEY=${publicKey}`,
    `VAPID_PRIVATE_KEY=${privateKey}`,
    "",
  ].join("\n");

  if (content.endsWith("\n")) return content + block;
  return content + "\n" + block;
}

function main() {
  if (!existsSync(rootEnv)) {
    console.error(`Missing ${rootEnv}. Copy from .env.example first.`);
    process.exit(1);
  }

  const existing = readFileSync(rootEnv, "utf8");
  if (hasVapidKeys(existing)) {
    console.log("VAPID keys already present in .env — no changes made.");
    console.log("Restart the API server if you recently added them.");
    return;
  }

  const keys = generateVapidKeysForSetup();
  const updated = appendVapidBlock(existing, keys.publicKey, keys.privateKey);
  writeFileSync(rootEnv, updated, "utf8");

  console.log("VAPID keys written to .env");
  console.log(`VAPID_SUBJECT=${subject}`);
  console.log(`VAPID_PUBLIC_KEY=${keys.publicKey}`);
  console.log("VAPID_PRIVATE_KEY=*** (saved in .env only)");
  console.log("\nRestart the API server, then refresh the staff profile page.");
}

main();
