// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/credentials/CardGrid.tsx": () => import("../components/mockups/credentials/CardGrid.tsx"),
  "./components/mockups/credentials/DataTable.tsx": () => import("../components/mockups/credentials/DataTable.tsx"),
  "./components/mockups/credentials/ListView.tsx": () => import("../components/mockups/credentials/ListView.tsx")
};
